---
- name: 'Download binary from https://releases.mattermost.com'
  get_url: 
    url: 'https://releases.mattermost.com/{{ mattermost_version }}/mattermost-team-{{ mattermost_version }}-linux-amd64.tar.gz'
    dest: "{{ global_cache_dir | mandatory }}/"
  when: not mattermost_enterprise
  become: false
  delegate_to: localhost

- name: 'Download enterprise version binary from https://releases.mattermost.com'
  get_url: 
    url: 'https://releases.mattermost.com/{{ mattermost_version }}/mattermost-{{ mattermost_version }}-linux-amd64.tar.gz'
    dest: "{{ global_cache_dir | mandatory }}/"
  when: mattermost_enterprise
  become: false
  delegate_to: localhost

- name: Unpack Mattermost archive
  unarchive: 
    src: "{{ global_cache_dir }}/mattermost-team-{{ mattermost_version }}-linux-amd64.tar.gz"
    dest: /opt/
  args:
    creates: /opt/mattermost/bin/platform
  when: not mattermost_enterprise

- name: Unpack Mattermost enterprise archive
  unarchive: 
    src: "{{ global_cache_dir }}/mattermost-{{ mattermost_version }}-linux-amd64.tar.gz"
    dest: /opt/
  args:
    creates: /opt/mattermost/bin/platform
  when: mattermost_enterprise

- name: Create user to run Mattermost service
  user: 
    name: "{{ mattermost_user }}"
    system: yes
    createhome: no 

- name: Create version file
  copy:
    content: "{{ mattermost_version }}"
    dest: /opt/mattermost/version
    force: yes
    owner: "{{ mattermost_user }}"
    mode: 0644
