---

- name: Check if a previous update wasn't deployed
  stat:
    path: /opt/mattermost-updated/mattermost
  register: mattermost_updated_stat

- import_tasks: deploy.yml
  when: mattermost_updated_stat.stat.exists

- name: Check if a previous mattermost version exists
  stat:
    path: /opt/mattermost/version
  register: previous_mattermost_version_stat

- name: Get the previous mattermost version
  slurp:
    src: /opt/mattermost/version
  register: previous_mattermost_version
  when: previous_mattermost_version_stat.stat.exists

- block:
  - import_tasks: update.yml
  - import_tasks: deploy.yml
  when: not previous_mattermost_version_stat.stat.exists or previous_mattermost_version['content'] | b64decode != mattermost_version
