---

- name: Check if the desired mattermost version exists
  stat:
    path: /opt/mattermost-versions/{{ mattermost_version }}
  register: mattermost_previous_stat

- import_tasks: update.yml
  when: not mattermost_previous_stat.stat.exists

- name: Check if any version is deployed
  stat:
    path: /opt/mattermost
  register: mattermost_symlink_stat

- name: Get the previous mattermost version
  set_fact:
    mattermost_previous_version: '{{ mattermost_symlink_stat.stat.lnk_target | basename }}'
  when: mattermost_symlink_stat.stat.lnk_target is defined

- import_tasks: deploy.yml
  when: mattermost_previous_version is not defined or mattermost_previous_version != mattermost_version

- import_tasks: collect-garbage.yml
