---
- name: Ensure database is created
  postgresql_db:
    name: "{{ mattermost_db_name }}"

- name: Ensure user has access to the database
  postgresql_user:
    db: "{{ mattermost_db_name }}"
    name: "{{ mattermost_db_user }}"
    password: "{{ mattermost_db_password }}"
    priv: ALL

- name: Ensure user does not have unnecessary privileges
  postgresql_user:
    name: "{{ mattermost_db_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
