- name: Reload nginx
  service:
    name: nginx.service
    state: reloaded
  listen: "restart services"

- name: Reload
  service:
    name: postgresql.service
    state: reloaded
  listen: "restart services"
